name: Update README with GitHub Activity

on:
  schedule:
    - cron: "*/30 * * * *" # Runs every 30 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        with:
          COMMIT_MSG: "⚡ Update README with recent activity"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

